function newData = select_bad_chan_GUI(d)

h = figure('Name', 'Check appropriate boxes', 'NumberTitle', 'off', 'MenuBar', 'none', 'ToolBar', 'none',...
    'Units', 'Normalized', 'Position', [0.4, 0.15, 0.2, 0.8]);
uit = uitable('Parent',h,...
    'Units', 'Normalized', 'Position', [0.1, 0.1, 0.8, 0.8],...
    'Data', table2cell(d),...
    'ColumnName',{'Label','bad chans','spikey','SOZ'},...
    'ColumnEditable',true,...
     'DeleteFcn','newData = MyDeleteFcn(gcbo);');


% newData = get(uit,'Data');
% set(uit,'CellEditCallback','newData = get(h,''Data'');');
% btn = uicontrol('Style', 'pushbutton', 'String', 'Update',...
%         'Position', [420 480 100 40],...
%         'Callback', 'newData = get(uit,''Data'');'); 
% newData = guidata(h);
waitfor(h)
newData = newData;
% newData = get(uit,'Data');
end